from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_getimage(object):
    def setupUi(self, getimage):
        getimage.setObjectName("getimage")
        getimage.resize(900, 700)
        # 栅格化布局
        self.gridLayoutWidget = QtWidgets.QWidget(getimage)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 901, 601))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(100, 50, 100, 30)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        # 选择视频按钮
        self.SelectVideo = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.SelectVideo.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SelectVideo.setFont(font)
        self.SelectVideo.setObjectName("SelectVideo")
        self.gridLayout.addWidget(self.SelectVideo, 0, 2, 1, 1)
        # 保存图片的路径按钮
        self.SavePicPath = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.SavePicPath.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SavePicPath.setFont(font)
        self.SavePicPath.setObjectName("SavePicPath")
        self.gridLayout.addWidget(self.SavePicPath, 1, 2, 1, 1)
        # 标签
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(130, 30))
        self.label.setBaseSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        # 视频路径文本框
        self.videopath = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.videopath.setMinimumSize(QtCore.QSize(246, 30))
        self.videopath.setObjectName("videopath")
        self.gridLayout.addWidget(self.videopath, 0, 1, 1, 1)
        # 保存图片路径文本框
        self.savepicpath = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.savepicpath.setMinimumSize(QtCore.QSize(246, 30))
        self.savepicpath.setObjectName("savepicpath")
        self.gridLayout.addWidget(self.savepicpath, 1, 1, 1, 1)
        # 标签
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(130, 30))
        self.label_2.setBaseSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        # 帧数间隔文本框
        self.framenum = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.framenum.setMinimumSize(QtCore.QSize(246, 30))
        self.framenum.setObjectName("framenum")
        self.gridLayout.addWidget(self.framenum, 2, 1, 1, 1)
        # 标签
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(130, 30))
        self.label_3.setBaseSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        # 底部横向布局
        self.horizontalLayoutWidget = QtWidgets.QWidget(getimage)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 600, 901, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(600, 20, 30, 20)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        # 确定以及退出按钮
        self.Confirm_get = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Confirm_get.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Confirm_get.setFont(font)
        self.Confirm_get.setObjectName("Confirm_get")
        self.horizontalLayout.addWidget(self.Confirm_get)
        self.Quit_get = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Quit_get.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Quit_get.setFont(font)
        self.Quit_get.setObjectName("Quit_get")
        self.horizontalLayout.addWidget(self.Quit_get)

        # 按钮点击事件指向
        self.retranslateUi(getimage)
        QtCore.QMetaObject.connectSlotsByName(getimage)

    # 元素内文本显示设置
    def retranslateUi(self, getimage):
        _translate = QtCore.QCoreApplication.translate
        getimage.setWindowTitle(_translate("getimage", "label"))
        self.SelectVideo.setText(_translate("getimage", "button"))
        self.SavePicPath.setText(_translate("getimage", "button"))
        self.label.setText(_translate("getimage", "label："))
        self.label_2.setText(_translate("getimage", "label："))
        self.label_3.setText(_translate("getimage", "label："))
        self.Confirm_get.setText(_translate("getimage", "button"))
        self.Quit_get.setText(_translate("getimage", "button"))